services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: